### PR TITLE
improve docs Update README.md

### PR DESCRIPTION
**Pull request by vikasverma84527**

### CODE REVIEW

**Comment by therealsujitk** [comment]
What?! This is spam

**Comment by therealsujitk** [comment]
Wth?! This is spam

**Comment by srinath1412001** [comment]
I agree with @therealsujitk

**Comment by eldadfux** [comment]
We love contribution, but we suggest you try and submit more meaningful PRs by exploring any of our [open issues](https://github.com/appwrite/appwrite/issues). If you have any problem or need help, please join our Discord community: https://appwrite.io/discord and use the #maintainers channel.

**Pull request closed without merging**
