### PR TITLE
Fixed the link to contribution guide

### LINKED ISSUE #4: Link to Contribution Guide
rename
The link to contribution guide is not working

### PR DESCRIPTION
**Pull request by srinath1412001**
closes #4 
Earlier the link to the contribution guide was not working.
rename

### CODE REVIEW

**Comment by therealsujitk** [comment]
Hi @srinath1412001! I''m not really a part of this repository, but I thought I should tell you, it would be cleaner if you replaced this:

```md
[contribution guide](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)
```

with this:

```md
[contribution guide](CONTRIBUTING.md)
```

This way, suppose someone forks this repository or has a copy somewhere else, the link would point to their `CONTRIBUTING.md` file.

**Comment by therealsujitk** [comment]
Good catch!

**Comment by eldadfux** [comment]
THANK YOU! All changes merged 🥳

Please reach out to me on our [Discord server](https://appwrite.io/discord) if you would like me to send you some cool Appwrite stickers and magnets! Please note that shipping might take longer times because of COVID19.

As a way of saying thank you, we have just invited you to join the Appwrite organization on GitHub. You can accept the invite by visiting https://github.com/orgs/appwrite/invitation. By joining our team, you will officially be an Appwrite maintainer on GitHub.

You can change your membership [visibility settings](https://help.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership), so your new Appwrite team membership badge will show up on your personal GitHub profile.

**Comment by therealsujitk** [comment]
Hey @eldadfux, the same issue is there in [appwrite/playground-for-flutter](https://github.com/appwrite/playground-for-flutter) too (tempting to fix it just to get free stuff lol). @srinath1412001 maybe you can fix this one too?

**Comment by srinath1412001** [comment]
Hey @therealsujitk ,
I have already made a PR in that repository too.

**Pull request merged**
